import Head from "next/head";
import {
  About,
  Contact,
  MainScreen,
  Navbar,
  Portfolio,
  Services,
  Testimonials,
} from "../components";

export default function Home() {
  return (
    <div className="min-h-screen text-white bg-black">
      <Head>
        <title>Divine Creations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/LoGo.ico" />
      </Head>

      <main className="overflow-x-hidden pottaOne">
        <Navbar />
        <section className="my-24 section md:min-h-screen">
          <MainScreen />
        </section>
        <section className="section" id="services">
          <Services />
        </section>
        <section className="section" id="portfolio">
          <Portfolio />
        </section>
        <section className="section" id="about">
          <About />
        </section>
        <section className="section" id="testimonials">
          <Testimonials />
        </section>
        <section className="section" id="contact">
          <Contact />
        </section>
      </main>
    </div>
  );
}
