import Head from "next/head";
import { Contact, MainScreen, Testimonials } from "../components";
import About from "../components/About";
import Portfolio from "../components/Portfolio";
import Services from "../components/Services";

export default function Home() {
  return (
    <div className="relative">
      <Head>
        <title>Divine Creations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/LoGo.png" />
      </Head>

      <main className="pottaOne bg-blue-50">
        <section className="section">
          <MainScreen />
        </section>
        <section className="section" id="services">
          <Services />
        </section>
        <section className="section" id="portfolio">
          <Portfolio />
        </section>
        <section className="section" id="about">
          <About />
        </section>
        <section className="section" id="testimonials">
          <Testimonials />
        </section>
        <section className="section" id="contact">
          <Contact />
        </section>
      </main>
    </div>
  );
}
